// <auto-generated />
namespace ToDoAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ToDoTablosunaAnnotationEklendi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ToDoTablosunaAnnotationEklendi));
        
        string IMigrationMetadata.Id
        {
            get { return "202308011220012_ToDoTablosunaAnnotationEklendi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
